name: flutter_salesforce_marketing_cloud
description: A new flutter plugin project.
version: 0.0.1
author: Abraao Lima
homepage: https://github.com/brotoo25/flutter_salesforce_marketing_cloud_sdk

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.abraaolima.flutter_salesforce_marketing_cloud
        pluginClass: FlutterSalesforceMarketingCloudPlugin
      ios:
        pluginClass: FlutterSalesforceMarketingCloudPlugin
